### ISSUE TITLE
What is the LDAmapping function?

### ISSUE THREAD

**Issue by mix4242** [JaeyoungShin/hybrid-BCI#2]
As per title. It appears in classification/classification_eeg.m (line 154) for example:
```MATLAB
C.eeg = train_RLDAshrink(fv_train.eeg,y_train); % shrinkage linear discriminant analysis
grouphat.eeg(foldIdx,:) = LDAmapping(C.eeg,fv_test.eeg); % use custom function
```

What is it? Where is it defined? MATLAB cant find it.

**Comment by mix4242** [comment]
@JaeyoungShin

**Comment by JaeyoungShin** [comment]
Please replace it with 'proc_linearDerivation.m'. It works in the same way.
For more details, please see the function help.

**Comment by mix4242** [comment]
Thanks for your response @JaeyoungShin . I tried applying what you recommend with no luck. Could you provide a code extract that I can use?

I also wonder how it will work. 'train_RLDAshrink' from the previous line returns a classifier structure containing the hyperplane that splits the training data. However the function you propose expects a 'spatial filter matrix'. How do I get this matrix? 

I've also tried applying 'apply_separatingHyperplane.m' as I thought maybe it be appropriate however while the code runs, it returns just a flat line at y=0 and x [-7, 25]. 

Any help is much appreciated :)

**Comment by RuixueLiu** [comment]
@JaeyoungShin  I am also running into this issue, i also tried proc_linearDerivation.m, it won't work. apply_separatingHyperplane.m won't work as well. Could you help with this? Thanks!

**Comment by JaeyoungShin** [comment]
> @JaeyoungShin I am also running into this issue, i also tried proc_linearDerivation.m, it won't work. apply_separatingHyperplane.m won't work as well. Could you help with this? Thanks!

Dear RuixueLiu, 

Please check the dimension of the feature vector you want to use. It must be a 2-dimensional vector as far as I know.  Please check the order of the vector array. the vector should be ordered as [number of features, number of observations(trials)] (see the apply_separatingHyperplane.m).

**Comment by miladalipour99** [comment]
@JaeyoungShin I am also running into this issue, i also tried proc_linearDerivation.m, it won't work.
this is the error 
"Error using misc_checkType (line 249)
Missing obligatory field(s) in variable 'dat': x, clab
Error in proc_linearDerivation (line 38)
misc_checkType(dat,  'STRUCT(x clab)');"

I checked the dimension of the feature vector I want to use
It is 2-dimensional vector and vector ordered as you said

**Comment by miladalipour99** [comment]
@JaeyoungShin I am also running into this issue, i also tried proc_linearDerivation.m, it won't work.
this is the error
"Error using misc_checkType (line 249)
Missing obligatory field(s) in variable 'dat': x, clab
Error in proc_linearDerivation (line 38)
misc_checkType(dat, 'STRUCT(x clab)');"

I checked the dimension of the feature vector I want to use
It is 2-dimensional vector and vector ordered as you said
